"""empty message

Revision ID: 59de8f12e41b
Revises: 
Create Date: 2018-05-23 11:44:16.306411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59de8f12e41b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
